# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNAskApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cntag',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
