# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 19:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('CNAskApp', '0002_cntag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnanswer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='cnprofile',
            name='username_override',
        ),
        migrations.RemoveField(
            model_name='cnquestion',
            name='images',
        ),
        migrations.AddField(
            model_name='cnanswer',
            name='attachments',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Прикрепления'),
        ),
        migrations.AddField(
            model_name='cnquestion',
            name='attachments',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Прикрепления'),
        ),
        migrations.AlterField(
            model_name='cnprofile',
            name='info',
            field=models.TextField(default='', max_length=2000, verbose_name='Краткая информация'),
        ),
        migrations.AlterField(
            model_name='cnprofile',
            name='status',
            field=models.TextField(default='', max_length=255, verbose_name='Статус'),
        ),
    ]
