# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNAskApp', '0005_auto_20161117_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnquestion',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
