# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNAskApp', '0006_cnquestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnquestion',
            name='tags',
            field=models.ManyToManyField(to='CNAskApp.CNTag'),
        ),
    ]
