# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNAskApp', '0008_auto_20161118_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnquestion',
            name='has_answers',
        ),
        migrations.AddField(
            model_name='cnquestion',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
