# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNAskApp', '0010_cnprofile_questions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnanswer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='cnquestion',
            name='tags',
        ),
    ]
